name: pucknotes
services:
  database:
    image: mongo:latest
    container_name: pucknotes-database
    restart: always
    volumes:
      - ./data/:/data/db/
  
  backend:
    container_name: pucknotes-backend
    build: server
    depends_on:
      - database
    ports:
      - ${BACKEND_PORT}:8080
    volumes:
      - /app/target
    environment:
      SPRING_DATA_MONGODB_URI: ${BACKEND_MONGO_URI}
    develop:
      watch:
        - action: rebuild
          path: server/src
          target: /app
 
  frontend:
    container_name: pucknotes-frontend
    build: client
    depends_on:
      - backend
    restart: always
    ports:
      - ${FRONTEND_PORT}:8080
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_BACKEND_URL: http://backend:${BACKEND_PORT}
    develop:
      watch:
        - action: rebuild
          path: client/src
          target: /app/src
          ignore:
            - node_modules