name: pucknotes
services:
  site:
    container_name: pucknotes-site
    build: .
    ports:
      - ${BACKEND_PORT}:8080
    environment:
      SPRING_DATA_MONGODB_URI: ${BACKEND_MONGO_URI}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
    develop:
      watch:
        - action: rebuild
          path: server/src
          target: /app