version: 3
silent: true
dotenv: ['.env']

tasks:
  dev: docker compose -f compose.dev.yml up --watch --build --remove-orphans

  scraper:
    dir: scraper
    cmds:
      - source .venv/bin/activate
      - python app.py

  database: mongosh "mongodb://localhost:${DATABASE_PORT}/data"