version: 3
silent: true
dotenv: ['.env']

tasks:
  backend:
    dir: server
    cmd: ./mvnw spring-boot:run

  frontend:
    dir: client
    cmd: npm run dev

  scraper:
    dir: scraper
    env:
      MONGO_SERVER_ADDR: "{{.BACKEND_MONGO_URI}}"
    cmds:
      - source .venv/bin/activate
      - python app.py

  database: mongosh "{{.BACKEND_MONGO_URI}}"