package Pucknotes.Server.Major;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;
import org.springframework.data.mongodb.core.mapping.FieldType;

/**
 * The Major class represents an academic major within a university system.
 * This class is mapped to the "majors" collection in a MongoDB database,
 * where each instance corresponds to a record of a specific major with its
 * associated properties.
 */
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "majors")
public class Major {

  /**
   * The unique identifier for each Major instance, automatically generated by MongoDB.
   */
  @Id
  private String id;

  /**
   * A unique code associated with the Major. This could be used for
   * identification or registration processes.
   */
  private String code;

  /**
   * The name of the Major, which provides a human-readable identification
   * for the field of study.
   */
  private String name;

  /**
   * The school or department that offers this Major. It is represented as
   * an Object ID to facilitate relationships with other collections, such
   * as those representing schools or departments in the database.
   */
  @Field(targetType = FieldType.OBJECT_ID)
  private String school;

  /**
   * The semester in which the Major is typically offered. This helps
   * in organizing and planning academic offerings and schedules.
   */
  @Field(targetType = FieldType.OBJECT_ID)
  private String semester;
}
