name: Deploy to Railway.

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: bervProject/railway-deploy@main
        with:
            railway_token: ${{ secrets.RAILWAY_TOKEN }}
            service: ${{ secrets.RAILWAY_SERVICE }}